# Random Sampling with Numpy

In [3]:
import numpy as np
import random

In [16]:
np.random.random(3)

array([0.18263144, 0.82608225, 0.10540183])

In [7]:
np.random.random((3,3))

array([[0.24212004, 0.72149046, 0.23274821],
       [0.00801044, 0.37299104, 0.47966508],
       [0.52995081, 0.61401268, 0.23870922]])

In [8]:
np.random.randint(1,4)

1

In [9]:
np.random.randint(1,4,(4,4))

array([[3, 2, 1, 3],
       [2, 3, 3, 3],
       [2, 2, 3, 3],
       [2, 3, 2, 1]])

In [10]:
np.random.randint(1,4,(2,4,4))

array([[[3, 1, 1, 3],
        [1, 3, 3, 3],
        [1, 3, 2, 1],
        [2, 3, 2, 1]],

       [[1, 3, 2, 2],
        [3, 2, 2, 1],
        [2, 1, 3, 1],
        [2, 2, 3, 2]]])

In [11]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4,(2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
2**32 -1

4294967295

In [15]:
np.random.rand(3)

array([0.41366737, 0.77872881, 0.58390137])

In [17]:
np.random.rand(3,3)

array([[0.28357668, 0.06556327, 0.05644419],
       [0.76545582, 0.01178803, 0.61194334],
       [0.33188226, 0.55964837, 0.33549965]])

In [18]:
np.random.randn(3,3)

array([[-0.74620143, -0.15662666, -0.19363594],
       [ 1.13912535,  0.36221796, -0.59091299],
       [ 0.38936304, -0.52699615, -0.51430791]])

In [20]:
x=[1,2,3,4]
np.random.choice(x)

1

In [21]:
np.random.choice(x)

3

In [22]:
for i in range(20):
    print(np.random.choice(x))

3
1
4
2
1
4
2
3
3
2
3
3
4
1
1
1
1
3
3
2


In [23]:
np.random.permutation(x)

array([4, 3, 1, 2])

In [24]:
np.random.permutation(x)

array([1, 4, 2, 3])