# Numpy Functions :

In [1]:
import numpy as np

## arange()

In [2]:
#np.arange(start,End,steps)
ar_1d=np.arange(1,13)
print(ar_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [3]:
even_ar=np.arange(1,13,2)
print(even_ar)

[ 1  3  5  7  9 11]


# linspace()

In [4]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# reshape()

In [5]:
ar_2d=ar_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
ar_3d=ar_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
ar=np.arange(1,13).reshape(2,6)
print(ar)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


# ravel

In [23]:
ar.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [24]:
ar.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [20]:
ar.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [21]:
ar.T

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])

In [1]:
list(reversed(range(1,11)))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [5]:
num_list=[21,13,19,3,11,5,18]
num_list.sort()
num_list[len(num_list)//2]

13

In [8]:
fruit_info={
    'fruit':'apple',
    'count':2,
    'price':3.5
}

In [12]:
my_keys=fruit_info.keys

In [14]:
from math import sin

In [15]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a*b
d=np.dot(a,b)

In [16]:
print(d)

32


In [17]:
print(c)

[ 4 10 18]


In [18]:
c=[a[0]*b[0],a[1]*b[1],a[2]*b[2]]
d=sum(c)

In [19]:
print(c,d)

[4, 10, 18] 32
