In [4]:
import numpy as np

In [2]:
np.__version__

'1.22.2'

In [3]:
arr_1d=np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [4]:
arr_1d.dtype # datatype

dtype('int32')

In [5]:
type(arr_1d) # variabletype

numpy.ndarray

In [6]:
arr_1d.ndim # dimentionality of an array

1

In [7]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr_2d.ndim

2

In [9]:
arr_1d.size

4

In [10]:
arr_2d.size

8

In [11]:
arr_2d.shape

(2, 4)

In [12]:
#(row,colm)

In [13]:
arr_2d.dtype

dtype('int32')

In [14]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
a=np.array([[[4,2]],[[4,2]]]) #(2,1,2)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[[4 2]]

 [[4 2]]]
<class 'numpy.ndarray'>
3
(2, 1, 2)
4


In [17]:
#array of dim "1" with shape as (6,)
a=np.array([1,2,3,5,6,8])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[1 2 3 5 6 8]
<class 'numpy.ndarray'>
1
(6,)
6


In [18]:
# #array of dim "2" with shape as (1,2)
a=np.array([[1,2]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[1 2]]
<class 'numpy.ndarray'>
2
(1, 2)
2


In [10]:
# #array of dim "2" with shape as (2,1)
a=np.array([[1],[2]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[1]
 [2]]
<class 'numpy.ndarray'>
2
(2, 1)
2


In [11]:
# #array of dim "2" with shape as (2,4)
a=np.array([[1,5,4,8],
            [2,8,7,9]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[1 5 4 8]
 [2 8 7 9]]
<class 'numpy.ndarray'>
2
(2, 4)
8


In [20]:
##array of dim "3" with shape as (1,2,3)
a=np.array([[[1,5,4],[2,8,7]]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 5 4]
  [2 8 7]]]
<class 'numpy.ndarray'>
3
(1, 2, 3)
6


In [21]:
# #array of dim "3" with shape as (3,2,1)
a=np.array([[[1],[2]],[[1],[2]],[[1],[2]]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[[1]
  [2]]

 [[1]
  [2]]

 [[1]
  [2]]]
<class 'numpy.ndarray'>
3
(3, 2, 1)
6


In [14]:
# #array of dim "3" with shape as (3,3,3)

(2,2,2)
a=np.array([[[],[]],[[],[]]])
a=np.array([[[1,2,3],
             [1,2,3],
             [1,2,3]],
            [[1,2,3],
             [1,2,3],
             [1,2,3]],
            [[1,2,3],
             [1,2,3],
             [1,2,3]]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
<class 'numpy.ndarray'>
3
(3, 3, 3)
27


In [15]:
# #array of dim "3" with shape as (2,1,2)
a=np.array([[[1,2]],[[1,2]]])
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
a=np.array([[[1,2],
             [1,2]],
            [[1,2],
             [1,2]]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

<class 'numpy.ndarray'>
3
(2, 1, 2)
4
[[[1 2]
  [1 2]]

 [[1 2]
  [1 2]]]
<class 'numpy.ndarray'>
3
(2, 2, 2)
8


In [24]:
x=np.array([4,7,9,10])
print(type(x))
print(x.shape)

<class 'numpy.ndarray'>
(4,)


In [25]:
print(x[0],x[1],x[2],x[3])  # numpy arrays are mutable.
x[0]=3
x[1]=6
x[2]=1

4 7 9 10


In [26]:
y= np.array([[3,5,7,6],[1,8,2,10]])
# indexing
print(y[0])
#Slicing
print(y[0,1:3])
#Stepping
print(y[0,::3])

[3 5 7 6]
[5 7]
[3 6]


In [27]:
#Stepping
print(y[:,::2])

[[3 7]
 [1 2]]


In [28]:
x=np.zeros([2,3])
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
x[0]=3

In [30]:
x

array([[3., 3., 3.],
       [0., 0., 0.]])

In [31]:
x[0,0]=5

In [32]:
x

array([[5., 3., 3.],
       [0., 0., 0.]])

In [33]:
x=np.zeros([3,3])
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
x[0]=5
x[1]=6
x[2]=7

In [35]:
x

array([[5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

In [36]:
x=np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
x=np.full((3,3),10)
x

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [38]:
x=np.eye(4)   # identity matrix
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
z=np.random.random((20,20))
z

array([[0.75644595, 0.98559206, 0.23577447, 0.45889981, 0.94204826,
        0.09276458, 0.78181238, 0.3187715 , 0.12090492, 0.76904905,
        0.11179796, 0.68835322, 0.48367261, 0.25850934, 0.60465941,
        0.1466262 , 0.54225628, 0.87709348, 0.37557466, 0.23943117],
       [0.93505917, 0.94862507, 0.13872974, 0.69059577, 0.14150879,
        0.87537825, 0.76949799, 0.25018474, 0.12258571, 0.80889708,
        0.15893407, 0.9805711 , 0.74283009, 0.91705112, 0.89587775,
        0.36949895, 0.53288621, 0.66919694, 0.45550108, 0.51620798],
       [0.35538099, 0.04832177, 0.26779767, 0.05195155, 0.00174463,
        0.7315603 , 0.40002218, 0.71389285, 0.21104945, 0.51521459,
        0.3552083 , 0.50218577, 0.03363131, 0.43602524, 0.40118848,
        0.82009497, 0.043894  , 0.96150175, 0.56842218, 0.95509653],
       [0.426013  , 0.56244255, 0.03975614, 0.74803861, 0.56495902,
        0.68782375, 0.43062157, 0.51445264, 0.1561298 , 0.02145834,
        0.26420933, 0.78797757, 0.32834694, 0

In [40]:
x=np.identity(4)  ##eye=identity
x

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:,1:2]

In [42]:
b

array([[ 2],
       [ 6],
       [10]])

In [43]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
b=a[:,:]

In [46]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
row_r1=a[2,:]
row_r1

array([ 9, 10, 11, 12])

In [51]:
col_2=a[:,2]
col_2

array([ 3,  7, 11])

In [54]:
x=np.array([[1,2],[4,5],[7,8]])
print(x[[0,1,2],[0,1,0]])

[1 5 7]


In [55]:
print(x[0,0],x[1,1],x[2,0])

1 5 7


In [56]:
print(x[[0,1,2],[0,1,0]] +2)  ##addition

[3 7 9]


In [58]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
y=np.array([0,2,0,1])

In [59]:
x[np.arange(4),y] +=10

In [60]:
x

array([[11,  2,  3],
       [ 4,  5, 16],
       [17,  8,  9],
       [10, 21, 12]])

In [64]:
#boolean array indexing
x=np.array([[4,3],[2,7],[5,9]])
bol_indx=(x>5)

In [65]:
bol_indx

array([[False, False],
       [False,  True],
       [False,  True]])

In [72]:
print(x[bol_indx])

[7 9]


In [73]:
y=x[0]

In [74]:
y

array([4, 3])

In [77]:
a=np.array([4.0,5.0,6.0])
print(a.dtype)

float64


In [78]:
a=np.array([4,5,6])
print(a.dtype)

int32


In [ ]:
###byte & bit ....1byte= Collection of 8 bits i.e. 0 1 0 1 1 0 1 0

In [87]:
## by default int is 32 bits
# min - 8 bits
# max - 64 bits


In [82]:
a=np.array([[4,5,6,8,12,45,55],[4,5,6,8,12,45,55]])
print(a.dtype)

int32


In [86]:
a=np.array([4,5,6],'int64')
a
print(a.dtype)

int64


In [90]:
a=np.array([4.0,5.0,6.0])  # by default - 64 bits
print(a.dtype)

float64


In [95]:
a=np.array([4.0,5.0,6.0],'float16')  # by default - 64 bits
print(a.dtype)                       # min - 16bits
                                     # max - 64 bits

float16


In [94]:
a=np.array([4j,5j,6j])    # by default 128 bits
print(a.dtype)            # min - 64 bits  
                          # max - 128 bits

complex128


In [3]:
a=np.array([[4,8],[2,6]],"float64")
b=np.array([[3,5],[1,8]],"float64")

In [4]:
print(a+b)

[[ 7. 13.]
 [ 3. 14.]]


In [6]:
np.add(a,b)

array([[ 7., 13.],
       [ 3., 14.]])

In [7]:
a=np.array([[4,8],[2,6]],"complex64")       # can convert "int" into "float" & "complex"
b=np.array([[3,5],[1,8]],"complex64")

In [8]:
print(a+b)

[[ 7.+0.j 13.+0.j]
 [ 3.+0.j 14.+0.j]]


In [12]:
a=np.array([[4.0,8.0],[2.0,6.0]],"complex64")       # can convert "int" into "float" & "complex"
b=np.array([[3.0,5.0],[1.0,8.0]],"complex64")
print(a+b)

[[ 7.+0.j 13.+0.j]
 [ 3.+0.j 14.+0.j]]


In [ ]:
a=np.array([[4.0,8.0],[2.0,6.0]],"complex64")       # can convert "int" into "float" & "complex"
b=np.array([[3.0,5.0],[1.0,8.0]],"complex64")
print(a+b)

In [15]:
print(a+b)

[[ 7.+0.j 13.+0.j]
 [ 3.+0.j 14.+0.j]]


In [16]:
print(np.subtract(a,b))

[[ 1.+0.j  3.+0.j]
 [ 1.+0.j -2.+0.j]]


In [17]:
print(np.multiply(a,b))

[[12.+0.j 40.+0.j]
 [ 2.+0.j 48.+0.j]]


In [18]:
print(np.divide(a,b))

[[1.3333334+0.j 1.6      +0.j]
 [2.       +0.j 0.75     +0.j]]


In [19]:
print(np.sqrt(a,b))

[[2.       +0.j 2.828427 +0.j]
 [1.4142135+0.j 2.4494898+0.j]]


In [24]:
a=np.array([[4,8],[2,6]])
b=np.array([[3,5],[1,8]])
c=np.array([4,6])
d=np.array([9,10])

In [25]:
print(a)
print(b)

[[4 8]
 [2 6]]
[[3 5]
 [1 8]]


In [23]:
print(a.dot(b))  #martix multiplication 1st row 1 column.

[[20 84]
 [12 58]]


In [26]:
print(np.dot(c,d))

96


In [31]:
x=np.array([[4,5],[6,7]])
print(np.sum(x,axis=1))

[ 9 13]


In [34]:
x=np.array([[[4,5],[6,7]]])
print(x.sum(x,axis=3))

TypeError: _sum() got multiple values for argument 'axis'

In [38]:
# Tronsposing
a=np.array([[4,8],[2,6]])
print(a.shape)
print(a.T.shape)

(2, 2)
(2, 2)


In [40]:
a=np.array([[[4,8,9],[2,6,5]]])
print(a)
print(a.T)

[[[4 8 9]
  [2 6 5]]]
[[[4]
  [2]]

 [[8]
  [6]]

 [[9]
  [5]]]


In [44]:
a=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(4, 3)
12


In [46]:
# brodcasting
a=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
b=np.array([1,2,3])
c=np.empty_like(a)
print(c)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [47]:
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(b)
print(type(b))
print(b.ndim)
print(b.shape)
print(b.size)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(4, 3)
12
[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
3


In [49]:
for i in range(4):
    c[i,:]=a[i,:]+b
print(c)

[[2 4 6]
 [5 7 9]
 [2 4 6]
 [5 7 9]]


In [61]:
a=np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
b=np.array([1,2,3])
c=np.tile(a,3)
print(c)

[[1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]
 [1 2 3 1 2 3 1 2 3]
 [4 5 6 4 5 6 4 5 6]]


In [64]:
a=np.array([[1,2,3],[4,5,6],[7,2,3],[0,5,6]])
b=np.array([1,2,3])
c=np.tile(a,(2,2))
print(c)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 2 3 7 2 3]
 [0 5 6 0 5 6]
 [1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 2 3 7 2 3]
 [0 5 6 0 5 6]]


In [74]:
d=np.array([[1,2,3],[4,5,6],[7,8,9],[0,5,6]])
e=np.array([0,0,3])
f=np.tile(e,(4,2))

In [75]:
c=d+f
print(c)

ValueError: operands could not be broadcast together with shapes (4,3) (4,6) 

In [78]:
x=np.array([4,5,6])
y=np.array([1,3])
print(np.reshape(x,(3,1))*y)

[[ 4 12]
 [ 5 15]
 [ 6 18]]
