In [2]:
import numpy as np

In [3]:
mx_1s=np.array([[1,1,1],[1,1,1],[1,1,1]]) # 3 by 3 array
print(mx_1s)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx_1s=np.ones(5)
print(mx_1s)

[1. 1. 1. 1. 1.]


In [5]:
mx_1s.dtype

dtype('float64')

In [9]:
mx_1s=np.ones((3,4))
print(mx_1s)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
mx_1s=np.ones((3,4),dtype=int)
print(mx_1s)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [7]:
mx_0s=np.zeros((4,6))
print(mx_0s)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [8]:
mx_0s=np.zeros((4,6),dtype=int)
print(mx_0s)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [9]:
mx_0s=np.zeros((4,6),dtype=bool)
print(mx_0s)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [10]:
mx_0s=np.zeros((4,6),dtype=str)
print(mx_0s)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [13]:
em_str=''
print(bool(em_str))

False


In [17]:
em_mx=np.empty((3,3))
print(em_mx)

[[0.00e+000 0.00e+000 0.00e+000]
 [0.00e+000 0.00e+000 5.89e-321]
 [0.00e+000 0.00e+000 0.00e+000]]
